Azure/kubernetes-hackfest

labs/build-application/README.md, labs/build-application/reg-acr.sh
The reg-acr.sh bash file can take the resource group, clustername, and ACR name and create the SPN.
=> Updated reg-acr.sh to accept parameters

labs/networking/ingress/README.md
Added prerequisite before begin step 1
=> Updated Lab: Configure Ingress Controller

labs/networking/ingress/README.md
Added target file path to change on Step 9
=> Updating Labs -> Networking -> Ingress

labs/cicd-automation/jenkins/Jenkinsfile
ACRNAME.ACRNAME doesn't get you an actual acr server address.
=> Fixing helm upgrade command

app-experimental/data-api/src/Gemfile.lock, app-experimental/open-sky-adapter-api/src/requirements.txt, app-experimental/open-sky-cronjob/src/requirements.txt
these were Github alerts. only in experimental code, but cleaning up
=> Fixed vulnerability alerts

app-experimental/auth-api/bin/www, app-experimental/auth-api/config/db-mongo.js, app-experimental/auth-api/routes/auth.js, app-experimental/kube-api/bin/www, app-experimental/kube-api/routes/nodes.js, app-experimental/kube-api/routes/pods.js, app/cache-api/app.js, app/cache-api/bin/www, app/cache-api/routes/api.js, app/data-api/app.js, app/data-api/bin/www, app/data-api/models/mongo/flights.js, app/data-api/models/mongo/latestFlight.js, app/data-api/models/mongo/latestQuake.js, app/data-api/models/mongo/latestWeather.js, app/data-api/models/mongo/quakes.js, app/data-api/models/mongo/weather.js, app/data-api/routes/api.js, app/flights-api/app.js, app/flights-api/bin/www, app/flights-api/routes/api.js, app/quakes-api/app.js, app/quakes-api/bin/www, app/quakes-api/routes/api.js, app/sample-go/css/site.css, app/sample-go/views/index.html, app/service-tracker-ui/vue.config.js
changed a lot of var to const in require statements at top of files to maintain consistency
clean up some formatting with prettier
=> update var to const in some places for consistency

README.md, charts/service-tracker-ui/templates/deployment.yaml, charts/service-tracker-ui/values.yaml, labs/scaling/README.md, labs/scaling/hpa.yaml
lab includes:
- scale deploy
- hpa
- cluster scale
- cluster autoscaler
=> Added scaling lab

labs/create-aks-cluster/README.md
Things are happening! (sorry, we caught this during today's training)
=> Version Bump

charts/data-api/values.yaml, charts/flights-api/values.yaml, charts/quakes-api/values.yaml, charts/weather-api/values.yaml, labs/create-aks-cluster/README.md, labs/helm-setup-deploy/README.md, labs/networking/ingress/README.md
- changed RG name to be unique
- cluster create lab checks for version before create
- changed API svcs to `ClusterIP` to preserve public IP's
- cleaned up other labs to match above changes
=> Updates for recent issues

labs/create-aks-cluster/README.md
az aks get-versions -l $LOCATION  > az aks get-versions -l $LOCATION -o table
=> format table

labs/create-aks-cluster/README.md
FIX the get-versions command - item 9
=> Update README.md - Lab1 Create AKS Cluster

labs/cicd-automation/jenkins/values.yaml
Please see https://github.com/helm/charts/commit/b02ae3f484a9ee73920f2dd5c3243a113e4c7dfe
=> Fix charts/jenkins/values.yaml. 

labs/cicd-automation/azure-devops/README.md, labs/monitoring-logging/prometheus-grafana/README.md, labs/monitoring-logging/prometheus-grafana/prom-graf-sample-go-app.yaml, labs/servicemesh/linkerd/README.md
minor edits:
- Azure DevOps
- Monitoring (prometheus)
- Service Mesh
=> Updated a few labs

labs/networking/README.md, labs/networking/network-policy/README.md, labs/networking/network-policy/block-access-to-data-api.yaml, labs/networking/network-policy/fix-access-data-api.yaml, labs/networking/network-policy/fix-access-namespace.yaml, labs/networking/network-policy/old-lab.md
Updated lab using new AKS CNI network policy feature
=> Updated Network Policy Lab

app-experimental/auth-api/package-lock.json, app-experimental/br-load/package-lock.json, app-experimental/cache-api/package-lock.json, app-experimental/flights-api/src/package-lock.json, app-experimental/geojson-subscriber/src/package-lock.json, app-experimental/kube-api/package-lock.json, app/data-api/package-lock.json, app/data-updater/package-lock.json, app/flights-api/package-lock.json, app/quakes-api/package-lock.json, app/service-tracker-ui/package-lock.json, app/weather-api/package-lock.json
used `npm audit fix` on app projects to update versions
=> fixed npm vulns

labs/networking/network-policy/README.md
Updated instructions for retrieving the subnet id and links to the correct Instrumentation Key documentation
=> Updated missing instructions network policy lab

labs/cicd-automation/brigade/README.md
https://azure.github.io/brigade => unable to access.
so i update the url to https://brigadecore.github.io/charts as per the installation guide: https://docs.brigade.sh/intro/install/
=> update helm chart url for brigade

labs/create-aks-cluster/README.md, labs/helm-setup-deploy/README.md
Reverts Azure/kubernetes-hackfest#133
Merged some brigade lab files accidentally that should not be in master, so backing out the PR and will resubmit.
=> Revert "Kubernetes Version Update and helm 3 note"

labs/monitoring-logging/azure-monitor/README.md, labs/networking/ingress/README.md
Minor updates to ingress and azure monitor labs
=> Griff lab fixes

labs/monitoring-logging/prometheus-grafana/README.md
Helm 3 users can skip step 1 on the prometheus lab as they dont need to set up rbac & tiller
=> Added note for helm 3 users on prometheus lab

labs/best-practices/operators/README.md
Remove name flag since it's no longer valid in Helm 3
=> Remove --name for Helm 3

app/data-updater/package-lock.json, app/data-updater/package.json
fixing the vuln in data updater
=> fixing vulnerabilities

labs/build-application/README.md
Just a small change to move along the deployment a little more quickly
=> Add --no-wait param to App Insights

labs/helm-setup-deploy/README.md
Removing the note on cache-api, since it doesn't exist in repo
=> Remove cache-api comment

labs/helm-setup-deploy/README.md
I am adding a piece of code in bash script to replace all acrServer values in Helm lab
=> Replace all acrServer values in Helm lab

labs/build-application/README.md, labs/create-aks-cluster/README.md, labs/helm-setup-deploy/README.md
Made updates to remove the dependency on .bashrc, fixed deprecated and updated content to the latest version data.
=> 0422 review
